# Site wide configuration

title: The Shifting
description: Bah
logo: 120x120.gif
teaser: 400x250.gif
locale: en_US
url: http://www.theshifting.ca

# Jekyll configuration

sass:
    sass_dir: _sass
    style: compressed
permalink: /:categories/:title/
markdown: kramdown
highlighter: pygments
gems:
  - jekyll-sitemap


# Site owner
owner:
  name: The Shifting
  email: someemail@later.com
  twitter: someuser
  google:
    ad-client: 
    ad-slot: 
  bio: "Hello. We are emerging artists. We shift around Vancouver."
  avatar: bio/shifting.png # 160x160 px image for author byline
disqus-shortname: theshifting


exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json"]
